
```{r}
rm(list = ls()) 
library(WGCNA)
library(reshape2)
library(stringr)
library(dplyr)
options(stringsAsFactors = F)
```

```{r}
load(file = 'input/step1.rdata')
datExpr = as.data.frame(t(exp1))

gsg = goodSamplesGenes(datExpr, verbose = 3)
gsg$allOK

sampleTree = hclust(dist(datExpr), method = "average")
sizeGrWindow(12,9) 
par(cex = 0.6)
par(mar = c(0,4,2,0))
plot(sampleTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5,
     cex.axis = 1.5, cex.main = 2)

allTraits <- as.data.frame(Group)
rownames(allTraits) <- rownames(datExpr)
allTraits$Control= ifelse(str_detect(allTraits$Group,"Control"),"1","0")
allTraits$Sebum= ifelse(str_detect(allTraits$Group,"Sebum"),"1","0")
datTraits <- allTraits[,2:3]
datTraits$Control <- as.numeric(datTraits$Control)
datTraits$Sebum <- as.numeric(datTraits$Sebum)

sampleTree2 = hclust(dist(datExpr), method = "average")

traitColors = numbers2colors(datTraits, signed = FALSE) 
plotDendroAndColors(sampleTree2, traitColors,
                    groupLabels = names(datTraits),
                    main = "Sample dendrogram and trait heatmap")
save(datExpr, datTraits, file = "input/FemaleLiver-01-dataInput.RData")
```

```{r}
rm(list = ls()) 
lnames = load(file = "input/FemaleLiver-01-dataInput.RData")

powers = c(c(1:10), seq(from = 12, to=30, by=2))
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 5)
sizeGrWindow(9, 5)
par(mfrow = c(1,2))
cex1 = 0.9

plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"))
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");abline(h=0.80,col="red")  

plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")

softPower <- sft$powerEstimate

```

```{r eval=FALSE, include=FALSE}

adjacency = adjacency(datExpr, power = softPower)

TOM = TOMsimilarity(adjacency)
dissTOM = 1-TOM
save(dissTOM ,file = "input/dissTOM.Rdate")
```

```{r}
load("input/dissTOM.Rdate")

geneTree = hclust(as.dist(dissTOM), method = "average")

plot(geneTree, xlab="", sub="", main = "Gene clustering on TOM-based dissimilarity", labels = FALSE, hang = 0.04)
```

```{r}

minModuleSize = 200

dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM, deepSplit = 2, pamRespectsDendro = FALSE, minClusterSize = minModuleSize) 

table(dynamicMods)

dynamicColors = labels2colors(dynamicMods)

table(dynamicColors)

plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut", dendroLabels = FALSE, hang = 0.03, addGuide = TRUE, guideHang = 0.05, main = "Gene dendrogram and module colors")

MEList = moduleEigengenes(datExpr, colors = dynamicColors)
MEs = MEList$eigengenes

MEDiss = 1-cor(MEs)

METree = hclust(as.dist(MEDiss), method = "average")

plot(METree, main = "Clustering of module eigengenes", xlab = "", sub = "")
```

```{r}
MEDissThres = 0.25

abline(h=MEDissThres, col = "red")

merge = mergeCloseModules(datExpr, dynamicColors, cutHeight = MEDissThres, verbose = 3)

mergedColors = merge$colors

mergedMEs = merge$newMEs

plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors), c("Dynamic Tree Cut", "Merged dynamic"), dendroLabels = FALSE, hang = 0.03, addGuide = TRUE, guideHang = 0.05)
```

```{r}

moduleColors = mergedColors

colorOrder = c("grey", standardColors(50))
moduleLabels = match(moduleColors, colorOrder)-1
MEs = mergedMEs

save(MEs, moduleLabels, moduleColors, geneTree, file= "input/networkConstruction-stepByStep.RData")
```

